//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinformFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllOrders
    {
        public int Id { get; set; }
        public Nullable<int> ConsumerID { get; set; }
        public Nullable<int> CarmadeID { get; set; }
        public string Carmake { get; set; }
        public Nullable<System.DateTime> PickedDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Consumers Consumers { get; set; }
        public virtual Mades Mades { get; set; }
    }
}
