//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinformFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WinFormFinalProjectEntities2 : DbContext
    {
        public WinFormFinalProjectEntities2()
            : base("name=WinFormFinalProjectEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Consumers> Consumers { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Mades> Mades { get; set; }
        public virtual DbSet<AllOrders> AllOrders { get; set; }
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
    }
}
